-- Unity Catalog registration intent for the synthetic developer-behavior dataset.
-- Generated by src/datagen (datagen.writer.unity_catalog_ddl). Synthetic data only.
-- Derived purely from src/datagen/schemas.py: identical for every run,
-- independent of seed, user count, month count or sample fraction.
-- Regenerate with: python -m datagen --emit-ddl sql/unity_catalog.sql

CREATE CATALOG IF NOT EXISTS dev_behavior;
CREATE SCHEMA IF NOT EXISTS dev_behavior.bronze;
CREATE SCHEMA IF NOT EXISTS dev_behavior.gold;

-- users: The Pro-tier user dimension: signup, geography, persona and the power-user flag derived from observed daily engagement.
--   data asset: VA (identity / persona / entitlements)
--   grain: one row per Pro-tier user
CREATE TABLE IF NOT EXISTS dev_behavior.bronze.users (
  user_id STRING NOT NULL COMMENT 'Synthetic surrogate user key, `USR-########`.',
  signup_date DATE NOT NULL COMMENT 'Date the user first became a Pro subscriber.',
  geo STRING NOT NULL COMMENT 'Region code: NA, EMEA, APAC, LATAM, MEA, ANZ.',
  country STRING NOT NULL COMMENT 'ISO-3166 alpha-2 country within the region.',
  plan STRING NOT NULL COMMENT 'Plan at signup (see `subscriptions.plan_id`).',
  tier STRING NOT NULL COMMENT 'Subscription tier; always `pro` in this dataset.',
  persona STRING NOT NULL COMMENT 'Value-add persona label for CRM targeting.',
  company_size STRING NOT NULL COMMENT 'Self-reported company-size bucket.',
  acquisition_channel STRING NOT NULL COMMENT 'How the user was acquired.',
  primary_language STRING NOT NULL COMMENT 'Most-used programming language.',
  ide_theme STRING NOT NULL COMMENT 'Cosmetic preference; a deliberate non-signal.',
  power_user_flag BOOLEAN NOT NULL COMMENT 'TRUE for SUSTAINED power users. A week qualifies when the user hit >=4 coding hours/day on >=5 days; a month qualifies when it contains a qualifying week. The flag is TRUE when qualifying months are at least half of the months the user was active, over >=2 active months. Note this is stricter than ''ever qualified once'' (which would flag ~37% of an 18-month population, including now-dormant users). Recomputable from usage_events.',
  tenure_days_at_window_end BIGINT NOT NULL COMMENT 'Days from signup to the end of the observation window.'
)
USING DELTA
PARTITIONED BY (geo)
COMMENT 'The Pro-tier user dimension: signup, geography, persona and the power-user flag derived from observed daily engagement.'
;
ALTER TABLE dev_behavior.bronze.users ADD CONSTRAINT users_pk PRIMARY KEY (user_id);

-- subscriptions: Subscription lifecycle and billing history: signup, renewals, downgrades and cancellation, with recognised revenue per term.
--   data asset: A03 — subscription plans & billing history
--   grain: one row per subscription term (a plan a user held for a period)
CREATE TABLE IF NOT EXISTS dev_behavior.bronze.subscriptions (
  subscription_id STRING NOT NULL COMMENT 'Surrogate key, `SUB-#########`.',
  user_id STRING NOT NULL COMMENT 'FK to `users.user_id`.',
  plan_id STRING NOT NULL COMMENT 'Plan held during this term.',
  plan_name STRING NOT NULL COMMENT 'Human-readable plan name.',
  tier STRING NOT NULL COMMENT 'Tier of the plan held (`pro`).',
  billing_period STRING NOT NULL COMMENT '`monthly` or `annual`.',
  mrr_usd DOUBLE NOT NULL COMMENT 'Monthly recurring revenue for this term.',
  list_price_usd DOUBLE NOT NULL COMMENT 'Sticker price per billing period.',
  term_start_date DATE NOT NULL COMMENT 'First day the user held this plan.',
  term_end_date DATE COMMENT 'Last day of the term; NULL while the term is still open.',
  term_index BIGINT NOT NULL COMMENT '0-based sequence of terms for the user.',
  status STRING NOT NULL COMMENT '`active`, `downgraded`, `canceled`, or `churned_after_reactivation`.',
  renewals_count BIGINT NOT NULL COMMENT 'Successful renewals billed in this term.',
  payment_failures BIGINT NOT NULL COMMENT 'Failed payment attempts in this term.',
  is_downgrade BOOLEAN NOT NULL COMMENT 'TRUE if this term began as a downgrade.',
  is_reactivation BOOLEAN NOT NULL COMMENT 'TRUE if this term began as a winback.',
  cancel_date DATE COMMENT 'Date the subscription was canceled; NULL if not canceled.',
  cancel_reason STRING COMMENT 'Reason code for cancellation; NULL if not canceled.',
  revenue_usd DOUBLE NOT NULL COMMENT 'Revenue recognised over the term.'
)
USING DELTA
COMMENT 'Subscription lifecycle and billing history: signup, renewals, downgrades and cancellation, with recognised revenue per term.'
;
ALTER TABLE dev_behavior.bronze.subscriptions ADD CONSTRAINT subscriptions_pk PRIMARY KEY (subscription_id);
ALTER TABLE dev_behavior.bronze.subscriptions ADD CONSTRAINT subscriptions_user_id_fk FOREIGN KEY (user_id) REFERENCES dev_behavior.bronze.users(user_id);

-- usage_events: The daily behavioural signal and the Structured Streaming / Lakeflow ingest source: active coding hours, AI-suggestion acceptance rate and session frequency. Only active days are emitted, so row count is well below users x days.
--   data asset: A06 — raw product usage events & telemetry
--   grain: one row per user per ACTIVE day (inactive days are not emitted)
CREATE TABLE IF NOT EXISTS dev_behavior.bronze.usage_events (
  event_date DATE NOT NULL COMMENT 'Activity date (partition column).',
  user_id STRING NOT NULL COMMENT 'FK to `users.user_id`.',
  geo STRING NOT NULL COMMENT 'Denormalised region code for partition pruning.',
  coding_hours DOUBLE NOT NULL COMMENT 'Active coding hours that day (editor-focused time), 0.05-16.',
  ai_suggestion_acceptance_rate DOUBLE NOT NULL COMMENT 'Accepted AI suggestions / suggestions shown that day, 0-1.',
  session_frequency BIGINT NOT NULL COMMENT 'Distinct editor sessions started that day.',
  suggestions_shown BIGINT NOT NULL COMMENT 'AI suggestions surfaced that day.',
  suggestions_accepted BIGINT NOT NULL COMMENT 'AI suggestions accepted that day.',
  lines_of_code_written BIGINT NOT NULL COMMENT 'Net lines written that day.',
  files_touched BIGINT NOT NULL COMMENT 'Distinct files edited that day.',
  ai_requests BIGINT NOT NULL COMMENT 'Chat / agent requests issued that day.',
  is_weekend BOOLEAN NOT NULL COMMENT 'TRUE for Saturday/Sunday activity.'
)
USING DELTA
PARTITIONED BY (event_date)
COMMENT 'The daily behavioural signal and the Structured Streaming / Lakeflow ingest source: active coding hours, AI-suggestion acceptance rate and session frequency. Only active days are emitted, so row count is well below users x days.'
;
ALTER TABLE dev_behavior.bronze.usage_events ADD CONSTRAINT usage_events_pk PRIMARY KEY (user_id, event_date);
ALTER TABLE dev_behavior.bronze.usage_events ADD CONSTRAINT usage_events_user_id_fk FOREIGN KEY (user_id) REFERENCES dev_behavior.bronze.users(user_id);

-- feature_adoption: Monthly adoption and activation intensity for the stickiness features. Adoption suppresses churn hazard, so this is a first-class model input.
--   data asset: A07 — feature adoption & activation metrics
--   grain: one row per user per feature per month
CREATE TABLE IF NOT EXISTS dev_behavior.bronze.feature_adoption (
  month_start DATE NOT NULL COMMENT 'First day of the calendar month.',
  user_id STRING NOT NULL COMMENT 'FK to `users.user_id`.',
  feature_key STRING NOT NULL COMMENT 'Stable feature identifier.',
  feature_name STRING NOT NULL COMMENT 'Human-readable feature name.',
  feature_family STRING NOT NULL COMMENT 'Feature grouping for rollups.',
  is_adopted BOOLEAN NOT NULL COMMENT 'TRUE if the user had activated it by then.',
  first_activation_date DATE COMMENT 'Date of first activation; NULL if never adopted.',
  activation_count BIGINT NOT NULL COMMENT 'Times the feature was used that month.',
  active_days BIGINT NOT NULL COMMENT 'Days that month the feature was used.',
  depth_score DOUBLE NOT NULL COMMENT '0-1 usage depth: how heavily the feature was used when available.'
)
USING DELTA
PARTITIONED BY (month_start)
COMMENT 'Monthly adoption and activation intensity for the stickiness features. Adoption suppresses churn hazard, so this is a first-class model input.'
;
ALTER TABLE dev_behavior.bronze.feature_adoption ADD CONSTRAINT feature_adoption_pk PRIMARY KEY (user_id, feature_key, month_start);
ALTER TABLE dev_behavior.bronze.feature_adoption ADD CONSTRAINT feature_adoption_user_id_fk FOREIGN KEY (user_id) REFERENCES dev_behavior.bronze.users(user_id);

-- support_tickets: Support friction as a churn signal: ticket volume, chat message volume, handling time and CSAT. Volume rises as engagement declines.
--   data asset: A14 — support tickets, chat logs & CSAT
--   grain: one row per support ticket
CREATE TABLE IF NOT EXISTS dev_behavior.bronze.support_tickets (
  ticket_id STRING NOT NULL COMMENT 'Surrogate key, `TCK-#########`.',
  user_id STRING NOT NULL COMMENT 'FK to `users.user_id`.',
  created_date DATE NOT NULL COMMENT 'Date the ticket was opened.',
  channel STRING NOT NULL COMMENT 'Contact channel used.',
  category STRING NOT NULL COMMENT 'Issue category.',
  priority STRING NOT NULL COMMENT 'Triaged priority, `P0_urgent`..`P3_low`.',
  chat_message_count BIGINT NOT NULL COMMENT 'Messages exchanged on the ticket.',
  first_response_minutes BIGINT NOT NULL COMMENT 'Minutes to first agent reply.',
  resolution_hours DOUBLE NOT NULL COMMENT 'Hours from open to resolution.',
  reopened_count BIGINT NOT NULL COMMENT 'Times the ticket was reopened.',
  is_escalated BOOLEAN NOT NULL COMMENT 'TRUE if escalated beyond tier-1 support.',
  csat_score DOUBLE COMMENT '1-5 satisfaction score; NULL when the user did not respond.',
  resolved BOOLEAN NOT NULL COMMENT 'TRUE if the ticket reached a resolved state.'
)
USING DELTA
COMMENT 'Support friction as a churn signal: ticket volume, chat message volume, handling time and CSAT. Volume rises as engagement declines.'
;
ALTER TABLE dev_behavior.bronze.support_tickets ADD CONSTRAINT support_tickets_pk PRIMARY KEY (ticket_id);
ALTER TABLE dev_behavior.bronze.support_tickets ADD CONSTRAINT support_tickets_user_id_fk FOREIGN KEY (user_id) REFERENCES dev_behavior.bronze.users(user_id);

-- crm_campaigns: Campaign dimension: objective, channel, target segment, budget, run dates.
--   data asset: VA (marketing saturation / campaign metadata)
--   grain: one row per CRM campaign
CREATE TABLE IF NOT EXISTS dev_behavior.bronze.crm_campaigns (
  campaign_id STRING NOT NULL COMMENT 'Campaign key, `CMP-###`.',
  campaign_name STRING NOT NULL COMMENT 'Human-readable campaign name.',
  objective STRING NOT NULL COMMENT '`retention`, `winback`, `adoption` or `expansion`.',
  channel STRING NOT NULL COMMENT '`email`, `in_app` or `push`.',
  target_segment STRING NOT NULL COMMENT 'Rule describing who is eligible.',
  offer_type STRING NOT NULL COMMENT 'What the touch offers the user.',
  budget_usd DOUBLE NOT NULL COMMENT 'Planned campaign budget.',
  start_date DATE NOT NULL COMMENT 'First day the campaign was live.',
  end_date DATE NOT NULL COMMENT 'Last day the campaign was live.',
  is_active_at_window_end BOOLEAN NOT NULL COMMENT 'TRUE if still live on the last day.'
)
USING DELTA
COMMENT 'Campaign dimension: objective, channel, target segment, budget, run dates.'
;
ALTER TABLE dev_behavior.bronze.crm_campaigns ADD CONSTRAINT crm_campaigns_pk PRIMARY KEY (campaign_id);

-- crm_touches: Individual campaign sends and their outcome. `outcome = 'reactivated'` is the numerator of the CRM reactivation-rate KPI.
--   data asset: VA (CRM touch + reactivation outcome)
--   grain: one row per campaign touch sent to a user
CREATE TABLE IF NOT EXISTS dev_behavior.bronze.crm_touches (
  touch_id STRING NOT NULL COMMENT 'Surrogate key, `TCH-##########`.',
  campaign_id STRING NOT NULL COMMENT 'FK to `crm_campaigns.campaign_id`.',
  user_id STRING NOT NULL COMMENT 'FK to `users.user_id`.',
  touch_date DATE NOT NULL COMMENT 'Date the touch was sent.',
  channel STRING NOT NULL COMMENT 'Channel the touch went out on.',
  message_variant STRING NOT NULL COMMENT 'A/B/C message variant.',
  delivered BOOLEAN NOT NULL COMMENT 'TRUE if the touch was delivered.',
  opened BOOLEAN NOT NULL COMMENT 'TRUE if the user opened it.',
  clicked BOOLEAN NOT NULL COMMENT 'TRUE if the user clicked through.',
  outcome STRING NOT NULL COMMENT '`reactivated`, `engaged_no_conversion`, `no_response` or `unsubscribed`.',
  reactivated BOOLEAN NOT NULL COMMENT 'Convenience flag: outcome == ''reactivated''.',
  user_state_at_touch STRING NOT NULL COMMENT '`active`, `at_risk` or `lapsed` when the touch was sent.',
  cost_usd DOUBLE NOT NULL COMMENT 'Marginal cost of the touch.'
)
USING DELTA
PARTITIONED BY (touch_date)
COMMENT 'Individual campaign sends and their outcome. `outcome = ''reactivated''` is the numerator of the CRM reactivation-rate KPI.'
;
ALTER TABLE dev_behavior.bronze.crm_touches ADD CONSTRAINT crm_touches_pk PRIMARY KEY (touch_id);
ALTER TABLE dev_behavior.bronze.crm_touches ADD CONSTRAINT crm_touches_user_id_fk FOREIGN KEY (user_id) REFERENCES dev_behavior.bronze.users(user_id);
ALTER TABLE dev_behavior.bronze.crm_touches ADD CONSTRAINT crm_touches_campaign_id_fk FOREIGN KEY (campaign_id) REFERENCES dev_behavior.bronze.crm_campaigns(campaign_id);

-- churn_labels: Per-user monthly churn label. `churned = TRUE` means the user was an active subscriber on the first day of the month and canceled during it. Rows only exist for months the user was at risk, so AVG(churned) is the monthly churn rate directly.
--   data asset: derived label (gold) — supervised training target
--   grain: one row per user per month the user was a subscriber at month start
CREATE TABLE IF NOT EXISTS dev_behavior.gold.churn_labels (
  month_start DATE NOT NULL COMMENT 'First day of the observation month.',
  user_id STRING NOT NULL COMMENT 'FK to `users.user_id`.',
  geo STRING NOT NULL COMMENT 'Denormalised region code.',
  churned BOOLEAN NOT NULL COMMENT 'THE LABEL: TRUE if the user canceled during this month.',
  churn_date DATE COMMENT 'Cancellation date when churned; NULL otherwise.',
  tenure_months BIGINT NOT NULL COMMENT 'Whole months from signup to month start.',
  is_power_user_month BOOLEAN NOT NULL COMMENT 'TRUE if the power-user bar was met.',
  active_days BIGINT NOT NULL COMMENT 'Active days observed that month.',
  avg_coding_hours DOUBLE NOT NULL COMMENT 'Mean coding hours over active days.',
  avg_acceptance_rate DOUBLE NOT NULL COMMENT 'Mean AI-acceptance over active days.',
  avg_session_frequency DOUBLE NOT NULL COMMENT 'Mean sessions/day over active days.',
  coding_hours_trend_30d DOUBLE NOT NULL COMMENT 'Ratio of this month''s mean coding hours to the prior month''s (1.0 = flat, <1 = declining). The headline decline feature.',
  support_tickets_30d BIGINT NOT NULL COMMENT 'Tickets opened during the month.',
  features_adopted BIGINT NOT NULL COMMENT 'Distinct stickiness features adopted.',
  crm_touches_30d BIGINT NOT NULL COMMENT 'CRM touches received during the month.'
)
USING DELTA
PARTITIONED BY (month_start)
COMMENT 'Per-user monthly churn label. `churned = TRUE` means the user was an active subscriber on the first day of the month and canceled during it. Rows only exist for months the user was at risk, so AVG(churned) is the monthly churn rate directly.'
;
ALTER TABLE dev_behavior.gold.churn_labels ADD CONSTRAINT churn_labels_pk PRIMARY KEY (user_id, month_start);
ALTER TABLE dev_behavior.gold.churn_labels ADD CONSTRAINT churn_labels_user_id_fk FOREIGN KEY (user_id) REFERENCES dev_behavior.bronze.users(user_id);

